########################################################################################################"
# "users" variable must be defined to be used in roles "Users_Create" and "Users_Faces"
########################################################################################################"

users:
  - name: dina
    password: "$6$pUS9Az3RZ8ieQaBh$.W5RVquKLgaPO/KRZG17bbGc7N/CL/k2sD6gO10ibIGwUBIQFiVRxRLnQQ1qJbMxmH26E59UwCzrhxcfjdKoc0"
    comment: Dina
    home: /home/dina
    createhome: yes

  - name: mateo
    password: $6$sK/zpS34PT20CZrD$ywQ4SVRZ5x0t1gIG/TwHaj5FC/A4ZV1EUZu1Wz4KdnypvWItR44egtYN90J2RKcOmcpnSTvNGfKpTCw4HPoKM.
    comment: Mateo
    home: /home/mateo
    createhome: yes  # Créer le répertoire home

  - name: elsa
    password: $6$DrBEAmX81LwH8l2X$jyG0.Fl3pGxiE9Ja7Bi/JD3ue/.7lj/6NLXjRUV0jK.Fgaw/F8gFWBJvChZgEbyBnGGOovpgF1Qv5QtofZ/ib0
    comment: Elsa
    home: /home/elsa
    createhome: yes  # Créer le répertoire home

########################################################################################################"
# "Network_Shares" variable must be defined to be used in role NFS_Mount
# name: describes your share
# type: nfs (smb not supported as of now)
# remote_dir: ip_adress:/remote_share
# local_dir: /local_share  (This directory will get created during the playbook execution)
########################################################################################################"

Network_Shares:
  - name: Backup
    type: nfs # NFS or SMB
    options: defaults,timeo=900,retrans=5,_netdev
    remote_dir: 192.168.2.110:/mnt/FastPool/Backup
    local_dir: /mnt/TrueNAS/Backup
  - name: Documents
    type: nfs # NFS or SMB
    options: defaults,timeo=900,retrans=5,_netdev
    remote_dir: 192.168.2.110:/mnt/FastPool/Documents
    local_dir: /mnt/TrueNAS/Documents
  - name: Downloads
    type: nfs # NFS or SMB
    options: defaults,timeo=900,retrans=5,_netdev
    remote_dir: 192.168.2.110:/mnt/FastPool/Downloads
    local_dir: /mnt/TrueNAS/Downloads
  - name: Elsa
    type: nfs # NFS or SMB
    options: defaults,timeo=900,retrans=5,_netdev
    remote_dir: 192.168.2.110:/mnt/FastPool/Elsa
    local_dir: /mnt/TrueNAS/Elsa
  - name: Etienne
    type: nfs # NFS or SMB
    options: defaults,timeo=900,retrans=5,_netdev
    remote_dir: 192.168.2.110:/mnt/FastPool/Etienne
    local_dir: /mnt/TrueNAS/Etienne
  - name: Gaming
    type: nfs # NFS or SMB
    options: defaults,timeo=900,retrans=5,_netdev
    remote_dir: 192.168.2.110:/mnt/FastPool/Gaming
    local_dir: /mnt/TrueNAS/Gaming
  - name: IT
    type: nfs # NFS or SMB
    options: defaults,timeo=900,retrans=5,_netdev
    remote_dir: 192.168.2.110:/mnt/FastPool/IT
    local_dir: /mnt/TrueNAS/IT
  - name: Mateo
    type: nfs # NFS or SMB
    options: defaults,timeo=900,retrans=5,_netdev
    remote_dir: 192.168.2.110:/mnt/FastPool/Mateo
    local_dir: /mnt/TrueNAS/Mateo
  - name: Music
    type: nfs # NFS or SMB
    options: defaults,timeo=900,retrans=5,_netdev
    remote_dir: 192.168.2.110:/mnt/FastPool/Music
    local_dir: /mnt/TrueNAS/Music
  - name: Photos
    type: nfs # NFS or SMB
    options: defaults,timeo=900,retrans=5,_netdev
    remote_dir: 192.168.2.110:/mnt/FastPool/Photos
    local_dir: /mnt/TrueNAS/Photos
  - name: Uploads
    type: nfs # NFS or SMB
    options: defaults,timeo=900,retrans=5,_netdev
    remote_dir: 192.168.2.110:/mnt/FastPool/Uploads
    local_dir: /mnt/TrueNAS/Uploads
  - name: Videos
    type: nfs # NFS or SMB
    options: defaults,timeo=900,retrans=5,_netdev
    remote_dir: 192.168.2.110:/mnt/FastPool/Videos
    local_dir: /mnt/TrueNAS/Videos

########################################################################################################"
# "Network_Shares" variable must be defined to be used in role NFS_Mount
# name: describes your share
# type: nfs (smb not supported as of now)
# remote_dir: ip_adress:/remote_share
# local_dir: /local_share  (This directory will get created during the playbook execution)
########################################################################################################"

Software:
  - name: Backup

Software_Flatpak:
  - name: Backup