# Edit with the users you want to create. By default all these users are non-admin and a home folder.

users_to_create:
  - name: dina
    password: "$6$pUS9Az3RZ8ieQaBh$.W5RVquKLgaPO/KRZG17bbGc7N/CL/k2sD6gO10ibIGwUBIQFiVRxRLnQQ1qJbMxmH26E59UwCzrhxcfjdKoc0"
    comment: Dina
    home: /home/dina
    createhome: yes

