- name: Software_My_Applications - Install for Arch Linux
  community.general.pacman:
    name:
      "{{ item }}"
    state: present
  with_items: "{{ Software_Archlinux }}"
  when: ansible_facts['distribution'] == "Archlinux"

#- name: Drivers_AMD - Install for Ubuntu & derivatives - Mesa Kisak
#  ansible.builtin.apt_repository:
#    repo: ppa:kisak/kisak-mesa
#  when: ansible_facts['distribution'] == "Ubuntu" or 
#        ansible_facts['distribution'] == "Zorin OS"


- name: Software_My_Applications - Install for OpenSuse
  community.general.zypper:
    name:
    - discord
    - steam
    state: present
  when: ansible_facts['distribution'] == "openSUSE Tumbleweed"



