---
- hosts: localhost
  become: true
  roles:
    - pacman_optimization
    - amd_drivers
    - bluetooth
#    - base_software
#    - kde_software
#    - game_compatibility
#    - fish_terminal
