---
- hosts: localhost
  become: true
  roles:
  ##### Ansible debug & requirements #####
    - Ansible_Facts
    - Ansible_Dependancies
  
  ##### System updates and base software #####
    - System_Update
    - Software_Base_Install

  ##### Drivers #####
    - Drivers_Bluetooth
    - Drivers_AMD
    - System_Update # Necessary following Mesa-kisak installation un Debian/Ubuntu

  ##### User environment #####
    - Share_Mount
    - Users_Create
    - Users_Faces
    - Users_KDE_Theme_Restore
  
  ##### Tweaks #####
    - Tweak_Game_Compatibility
    - Tweak_Neofetch_Customization
    - Tweak_NumLock_On
    - Tweak_PackageMgr_Customization

  ##### Softwares #####
    - Software_Fish_Install
    - Software_Floorp_Install
    - Software_KDE_Install
    - Software_My_Flatpaks
    - Flatpak_Core
    - Flatpak_Softwares

