- name: Create_Users - Add Linux Users
  ansible.builtin.user:
    name: "{{ item.name }}"
    password: "{{ item.password }}"
    comment: "{{ item.comment }}"
    home: "{{ item.home }}"
    createhome: "{{ item.createhome }}"
  with_items: "{{ users }}"
