#- name: Konsave - Downloading KDE Theme
#  become: true
#  shell: cp /mnt/TrueNAS/IT/Ansible/Etienne.knsv ~/

#- name: Konsave - Downloading binary
#  ansible.builtin.pip:
#    name: konsave
#    extra_args: --break-system-packages

- name: Install tox from git repository
  community.general.pipx:
    name: konsave
    source: git+https://github.com/Prayag2/konsave.git

- name: Konsave - Importing Etienne profile
  become: true
  shell: pipx run konsave -i /mnt/TrueNAS/IT/Ansible/Etienne.knsv

- name: Konsave - Applying Etienne profile
  become: true
  shell: pipx run konsave -a Etienne
