- name: Install KDE Software
  community.general.pacman:
   name:
    - okular
    - kdenlive
    - print-manager
    - gwenview
    - spectacle
    - partitionmanager
    - kdeplasma-addons
    - powerdevil
    - kcalc
    - plasma-systemmonitor
    - skanpage
    - ffmpegthumbs
    - qt6-wayland
    - qt6-multimedia
    - qt6-multimedia-gstreamer
    - qt6-multimedia-ffmpeg
   state: present

