vars:
  nfsmounts:
    - {  path: "/mnt/TrueNAS/Backup", src: "192.168.2.110:/mnt/FastPool/Backup" }
    - {  path: "/mnt/TrueNAS/Documents", src: "192.168.2.110:/mnt/FastPool/Documents" }
    - {  path: "/mnt/TrueNAS/Downloads", src: "192.168.2.110:/mnt/FastPool/Downloads" }
    - {  path: "/mnt/TrueNAS/Elsa", src: "192.168.2.110:/mnt/FastPool/Elsa" }
    - {  path: "/mnt/TrueNAS/Etienne", src: "192.168.2.110:/mnt/FastPool/Etienne" }
    - {  path: "/mnt/TrueNAS/Gaming", src: "192.168.2.110:/mnt/FastPool/Gaming" }
    - {  path: "/mnt/TrueNAS/IT", src: "192.168.2.110:/mnt/FastPool/IT" }
    - {  path: "/mnt/TrueNAS/Mateo", src: "192.168.2.110:/mnt/FastPool/Mateo" }
    - {  path: "/mnt/TrueNAS/Music", src: "192.168.2.110:/mnt/FastPool/Music" }
    - {  path: "/mnt/TrueNAS/Photos", src: "192.168.2.110:/mnt/FastPool/Photos" }
    - {  path: "/mnt/TrueNAS/Uploads", src: "192.168.2.110:/mnt/FastPool/Uploads" }
    - {  path: "/mnt/TrueNAS/Videos", src: "192.168.2.110:/mnt/FastPool/Videos" }
