- name: Installing Flatpak
  community.general.pacman:
   name:
    - flatpak
   state: present

- name: Add Flathub repository
  community.general.flatpak_remote:
    name: flathub
    state: present
    flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo
