- name: Installs AMD Drivers + Vulkan
  community.general.pacman:
   name:
    - mesa
    - lib32-mesa
    - vulkan-radeon
    - lib32-vulkan-radeon
    - vulkan-icd-loader
    - lib32-vulkan-icd-loader
    - vulkan-mesa-layers
    - lib32-vulkan-mesa-layers
   state: present
