- name: Drivers_AMD - Install for Arch Linux
  community.general.pacman:
    name:
    - lib32-mesa
    - vulkan-radeon
    - lib32-vulkan-radeon
    - vulkan-icd-loader
    - lib32-vulkan-icd-loader
    state: present
  when: ansible_facts['distribution'] == "Archlinux"

#- name: Drivers_AMD - Install for Debian/Ubuntu
#  ansible.builtin.apt:
#    name:
#    - gstreamer
#    - timeshift
#    state: present
#  when: ansible_facts['distribution'] == "Debian"

- name: Drivers_AMD - Install for OpenSuse
  community.general.zypper:
    name:
    - kernel-firmware-amdgpu
    - libdrm_amdgpu1
    - libdrm_amdgpu1-32bit
    - libdrm_radeon1
    - libdrm_radeon1-32bit
    - libvulkan_radeon
    - libvulkan_radeon-32bit
    - libvulkan1
    - libvulkan1-32bit
    state: present
  when: ansible_facts['distribution'] == "openSUSE Tumbleweed"
